db = 'r11grid.db'

[[files]]
name = 'grc'
train_source = 'generated/hbo-grc/hbo.input.bin'
train_target = 'generated/hbo-grc/grc.gold.bin'
test_source = 'generated/hbo-grc/hbo.input.bin' # TODO
test_target = 'generated/hbo-grc/grc.gold.bin' # TODO
sentences = 300

#[[files]]
#name = 'eng_kjv'
#train_source = 'generated/hbo-grc/hbo.input.bin'
#train_target = '...eng.bin'

[initial_parameters]
#initial_size = 200
#iterations = 50
initial_size = 200
iterations = 2
increment = 0
similarity = 0.9
filters = 25
errors = {cohorts = 1}

# ignore block for testing
[real_parameters]
initial_size = [50, 100, 200, 500, 1000]
iterations = [10, 20, 30, 50, 100, 200, 1000]
increment = [0, 10, 20, 30, 50, 100]
similarity = [0.7, 0.8, 0.85, 0.9, 0.95, 1]
filters = [10, 15, 20, 25, 30, 40, 50]

[parameters]
initial_size = [200, 250]
iterations = [2, 3]
increment = [0, 50]
similarity = [0.9, 0.95]
filters = [25, 30]

[[parameters.errors]]
cohorts = 1
# default

[[parameters.errors]]
missing_feats = 20
# prioritize features